import React from 'react'

const PageTwo = () => {
  return (
    <>
    <ul>
      <li> chotu Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia nulla, dolor quod, impedit totam atque pariatur aliquam amet, sed praesentium alias. Odio dignissimos debitis expedita voluptatem voluptas mollitia dolore vitae ut in quo nulla rem atque possimus, libero cumque? Placeat eius perspiciatis voluptas enim quia, perferendis tempora numquam voluptate dolorem excepturi suscipit repellendus itaque nihil. Dicta quo officia voluptas, obcaecati modi libero doloribus reprehenderit, ducimus eum excepturi, vero mollitia quaerat voluptatibus? Voluptas quo assumenda doloribus velit mollitia earum accusamus nulla, eum molestias ea totam fugiat sit deserunt, voluptatem commodi, molestiae perferendis voluptates rerum. Veritatis nulla dolores voluptas quo doloremque dolor.</li>
      <li> chotu Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia nulla, dolor quod, impedit totam atque pariatur aliquam amet, sed praesentium alias. Odio dignissimos debitis expedita voluptatem voluptas mollitia dolore vitae ut in quo nulla rem atque possimus, libero cumque? Placeat eius perspiciatis voluptas enim quia, perferendis tempora numquam voluptate dolorem excepturi suscipit repellendus itaque nihil. Dicta quo officia voluptas, obcaecati modi libero doloribus reprehenderit, ducimus eum excepturi, vero mollitia quaerat voluptatibus? Voluptas quo assumenda doloribus velit mollitia earum accusamus nulla, eum molestias ea totam fugiat sit deserunt, voluptatem commodi, molestiae perferendis voluptates rerum. Veritatis nulla dolores voluptas quo doloremque dolor.</li>
      <li> chotu Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia nulla, dolor quod, impedit totam atque pariatur aliquam amet, sed praesentium alias. Odio dignissimos debitis expedita voluptatem voluptas mollitia dolore vitae ut in quo nulla rem atque possimus, libero cumque? Placeat eius perspiciatis voluptas enim quia, perferendis tempora numquam voluptate dolorem excepturi suscipit repellendus itaque nihil. Dicta quo officia voluptas, obcaecati modi libero doloribus reprehenderit, ducimus eum excepturi, vero mollitia quaerat voluptatibus? Voluptas quo assumenda doloribus velit mollitia earum accusamus nulla, eum molestias ea totam fugiat sit deserunt, voluptatem commodi, molestiae perferendis voluptates rerum. Veritatis nulla dolores voluptas quo doloremque dolor.</li>
      <li> chotu Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia nulla, dolor quod, impedit totam atque pariatur aliquam amet, sed praesentium alias. Odio dignissimos debitis expedita voluptatem voluptas mollitia dolore vitae ut in quo nulla rem atque possimus, libero cumque? Placeat eius perspiciatis voluptas enim quia, perferendis tempora numquam voluptate dolorem excepturi suscipit repellendus itaque nihil. Dicta quo officia voluptas, obcaecati modi libero doloribus reprehenderit, ducimus eum excepturi, vero mollitia quaerat voluptatibus? Voluptas quo assumenda doloribus velit mollitia earum accusamus nulla, eum molestias ea totam fugiat sit deserunt, voluptatem commodi, molestiae perferendis voluptates rerum. Veritatis nulla dolores voluptas quo doloremque dolor.</li>
      <li> chotu Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia nulla, dolor quod, impedit totam atque pariatur aliquam amet, sed praesentium alias. Odio dignissimos debitis expedita voluptatem voluptas mollitia dolore vitae ut in quo nulla rem atque possimus, libero cumque? Placeat eius perspiciatis voluptas enim quia, perferendis tempora numquam voluptate dolorem excepturi suscipit repellendus itaque nihil. Dicta quo officia voluptas, obcaecati modi libero doloribus reprehenderit, ducimus eum excepturi, vero mollitia quaerat voluptatibus? Voluptas quo assumenda doloribus velit mollitia earum accusamus nulla, eum molestias ea totam fugiat sit deserunt, voluptatem commodi, molestiae perferendis voluptates rerum. Veritatis nulla dolores voluptas quo doloremque dolor.</li>
    </ul>
    
    </>
  )
}

export default PageTwo